theme: jekyll-theme-minimal
lang: en

url: https://imzeo.github.io

title: Zeo's homepage
description: Hello? World? Are we live already?

author:
  name: Zeo
  url: https://github.com/imZeo

github:
  username: imZeo
